import { NextResponse } from 'next/server';

export async function GET(request) {
    try {
        const { searchParams } = new URL(request.url);
        const provider = searchParams.get('provider');
        const returnUrl = searchParams.get('returnUrl');

        if (!returnUrl) {
            return NextResponse.json({ message: 'returnUrl is required' }, { status: 400 });
        }

        // Mock Response: Return a URL that simulates the Google Consent Screen
        // In a real app, this URL is generated by the Identity Provider (Google)
        // Here, we point to our internal "External Login Page" to verify flow.
        const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'; // Or origin from request

        // We construct the URL to our Mock Page, passing the returnUrl so it can redirect back found there.
        const separator = returnUrl.includes('?') ? '&' : '?';
        // We simply pass the "returnUrl" through to our Mock Page
        const targetUrl = `${baseUrl}/en/auth/external-login?provider=${provider}&returnUrl=${encodeURIComponent(returnUrl)}`;

        return NextResponse.json({
            url: targetUrl
        });

    } catch (error) {
        return NextResponse.json({ message: 'Failed to initiate external login' }, { status: 500 });
    }
}
